version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: assistencia_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gert
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-sql.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - assistencia_network

  # Serviço opcional de phpMyAdmin para administração do banco via navegador
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: assistencia_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - assistencia_network

volumes:
  mysql_data:
    driver: local

networks:
  assistencia_network:
    driver: bridge
